BOT_TOKEN: 
  - ODQ1MjczODkwMzIyMjUxNzg2.GYzS1e.BK1cKuWuO65HeLi3eNd3yQlBBpiUSgaR3gQZhI
CHANNEL_ID: 
  - 1061681370943979530
MODE: quote
REPLY: Y
SIMSIMI_LANG: 
DELAY: 60
DEL_AFTER: 
REPOST_LAST_CHAT: 100